config/routes.rb
Emprestimo::Application.routes.draw do
  resources :sessions
  resources :item_advances#, only: [:index, :edit, :update]
  resources :advances
  resources :caixas
  
  match '/item_advance_by_cliente/:id', :controller=>'item_advances', :action => 'item_advance_by_cliente', via: [:get]
  match '/item_advance_by_city/:id', :controller=>'item_advances', :action => 'item_advance_by_city', via: [:get]
  match '/cobranca_diaria_by_city/:id', :controller=>'item_advances', :action => 'cobranca_diaria_by_city', via: [:get]
  
  match '/advance_by_city/:id', :controller=>'advances', :action => 'advance_by_city', via: [:get]
  match '/select_client/', :controller=>'item_advances', :action => 'select_client', via: [:get]
  match '/summary_city/', :controller=>'item_advances', :action => 'summary_city', via: [:get]
  match '/select_city/', :controller=>'item_advances', :action => 'select_city', via: [:get]
  namespace "api" do
    resources :cidades
    resources :clientes
    resources :advances, except: [:destroy]
    resources :item_advances
    resources :empresas do
      resources :advances, only: [:destroy]
      resources :item_advances, only: [:destroy]
    end
    resources :caixas
    resources :lancamento_caixas
    post "cidades_uuid" => "cidades#cidades_uuid", :as => "cidades_uuid",  via: [:post]
    post "clientes_uuid" => "clientes#clientes_uuid", :as => "clientes_uuid",  via: [:post]
    #post "item_advances_today_and_city" => "item_advances#item_advances_today_and_city", :as => "item_advances_today_and_city",  via: [:post]
    post "item_advances_today_and_city" => "item_advances#item_advances_today_and_city",  via: [:post]
    get "is_active" => "servers#is_active", :as => "is_active", via: [:get]
  end
  #root to: 'item_advances#index'
  root to: 'sessions#new'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  

end
 

app/models/caixa.rb
class Caixa < ActiveRecord::Base
  has_many :lancamento_caixas

  def status_nome
  	case self.status
  	  when 0 then "Aberto"
  	  when 1 then "Fechado"
  	end
  end
end

app/controllers/api/caixas_controller.rb
class Api::CaixasController < ApiController
  def index
	@caixas = Caixa.all
	render json: @caixas
  end

  def show
  	@caixa = Caixa.find params[:id]
    render json: @caixa.to_json 
  end

  def create
    begin
      @caixa = Caixa.new(params[:caixa])
      empresa_id = params[:caixa][:empresa_id]
      puts ">>>>>>>>>>>>>>>> #{@caixa.to_json}"
      if @caixa.save
      	puts ">>>>>>>>>>>>>>>> Caixa was successfully created."
        render notice: 'Caixa was successfully created.'
      else
        @errors = { :errors => @caixa.errors.each {|m| m.to_s} }
        puts ">>>>>>>>>>>>>>>> @errors.to_json"
        render json: @errors.to_json, :status => 200
      end
    rescue Exception => e
      @errors = { :errors => "create, record empresa: #{ empresa_id } and caixa uuid: #{@caixa.descricao} not found" }
      render json: @errors.to_json, :status => 200
    end 

  end  

  def update
    begin
      @caixa = Caixa.find_by_empresa_id_and_uuid(params[:caixa][:empresa_id],params[:caixa][:uuid])
      if @caixa.update_attributes(params[:caixa])
        render notice: 'Caixa was successfully updated.'
      else
        @errors = { :errors => @caixa.errors.each {|m| m.to_s} }
        render json: @errors.to_json, :status => 200
      end
    rescue Exception => e
      @errors = { :errors => "update caixa, record empresa: #{ empresa_id } and caixa uuid: #{@caixa.descricao} not found" }
      render json: @errors.to_json, :status => 200
    end
  end

end

app/controllers/caixas_controller.rb
class CaixasController < ApplicationController
  before_action :signed_in_user

  respond_to :html

  def index
  	@cidades = Cliente.cidades(current_user.empresa_id)
  	#@cidades = Cliente.cidades(current_user.empresa_id)
  	@caixas = Caixa.where(empresa_id: current_user.empresa_id).order('data_abertura desc')
  end

  #def advance_by_city
  #  @advances = Advance.joins(:cliente).where("clientes.cidade = ?", params[:id])
  #  respond_with(@advances) do |format|
  #    format.html { render :layout => !request.xhr? }
  #  end
  #end

  def show
  	@caixa = Caixa.find(params[:id])
  end

end

app/views/caixas/index.html.erb
<h1>Listagem dos Caixas</h1>

<table class="table">
	<thead>
		<th>ID</th>
		<th>Caixa</th>
		<th>Data Abertura</th>
		<th>Hora Abertura</th>
		<th>Data Fechamento</th>
		<th>Hora Fechamento</th>
		<th>Saldo</th>
		<th>Status</th>
	</thead>
	
	<tbody>
		<% @caixas.each do |caixa| %>
		<tr>
			<td><%= link_to caixa.id, caixa_path(caixa.id) %></td>
			<td><%= link_to caixa.descricao, caixa_path(caixa.id) %></td>
			<td><%= link_to caixa.data_abertura.to_s, caixa_path(caixa.id) %></td>
			<td><%= link_to caixa.hora_abertura.strftime('%H:%M:%S'), caixa_path(caixa.id) %></td>
			<td><%= caixa.data_fechamento.to_s if !caixa.data_fechamento.nil? %></td>
			<td><%= caixa.hora_fechamento.strftime('%H:%M:%S') if !caixa.hora_fechamento.nil? %></td>
			<td><%= caixa.valor.to_f %></td>
			<td><%= caixa.status_nome %></td>
		</tr>
		<% end %>
	</tbody>

</table>

app/views/caixas/show.html.erb
<h4>Caixa: <%= @caixa.descricao %></h4>
<p>
  <strong>Data Abertura:</strong> 
  <%= @caixa.data_abertura.to_s %>
</p>

<p>
  <strong>Hora Abertura:</strong> 
  <%= @caixa.hora_abertura.strftime('%H:%M:%S') %>
</p>

<p>
  <strong>Data Fechamento:</strong> 
  <%= @caixa.data_fechamento.to_s %>
</p>

<p>
  <strong>Hora Fechamento:</strong> 
  <%= @caixa.hora_fechamento.strftime('%H:%M:%S') if !@caixa.hora_fechamento.nil? %>
</p>

<p>
  <strong>Valor:</strong> 
  <%= @caixa.valor.to_f %>
</p>

<% if @caixa.lancamento_caixas.size > 0 %>
  <h4>Lancamentos do Caixa</h4>
	<table class="table">
		<thead>
			<th>ID</th>
			<th>Data</th>
			<th>Credito</th>
			<th>Debito</th>
			<th>Descricao</th>
		</thead>
		
		<tbody>
			<% @caixa.lancamento_caixas.each do |lancamento| %>
			<tr>
				<td width="10%"><%= lancamento.id %></td>
				<td width="10%"><%= lancamento.data.to_s %></td>
				<td width="10%"><%= lancamento.credito.to_f %></td>
				<td width="10%"><%= lancamento.debito.to_f %></td>
				<td width="60%"><%= lancamento.descricao %></td>
			</tr>
			<% end %>
		</tbody>

	</table>  
<% end %>