config/routes.rb
Emprestimo::Application.routes.draw do
  resources :sessions
  resources :item_advances#, only: [:index, :edit, :update]
  resources :advances
  resources :caixas
  
  match '/item_advance_by_cliente/:id', :controller=>'item_advances', :action => 'item_advance_by_cliente', via: [:get]
  match '/item_advance_by_city/:id', :controller=>'item_advances', :action => 'item_advance_by_city', via: [:get]
  match '/cobranca_diaria_by_city/:id', :controller=>'item_advances', :action => 'cobranca_diaria_by_city', via: [:get]
  
  match '/advance_by_city/:id', :controller=>'advances', :action => 'advance_by_city', via: [:get]
  match '/select_client/', :controller=>'item_advances', :action => 'select_client', via: [:get]
  match '/summary_city/', :controller=>'item_advances', :action => 'summary_city', via: [:get]
  match '/select_city/', :controller=>'item_advances', :action => 'select_city', via: [:get]
  namespace "api" do
    resources :cidades
    resources :clientes
    resources :advances, except: [:destroy]
    resources :item_advances
    resources :empresas do
      resources :advances, only: [:destroy]
      resources :item_advances, only: [:destroy]
    end
    resources :caixas
    resources :lancamento_caixas
    post "cidades_uuid" => "cidades#cidades_uuid", :as => "cidades_uuid",  via: [:post]
    post "clientes_uuid" => "clientes#clientes_uuid", :as => "clientes_uuid",  via: [:post]
    #post "item_advances_today_and_city" => "item_advances#item_advances_today_and_city", :as => "item_advances_today_and_city",  via: [:post]
    post "item_advances_today_and_city" => "item_advances#item_advances_today_and_city",  via: [:post]
    get "is_active" => "servers#is_active", :as => "is_active", via: [:get]
  end
  #root to: 'item_advances#index'
  root to: 'sessions#new'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  

end
 

app/models/item_advance.rb
class ItemAdvance < ActiveRecord::Base
  belongs_to :advance
  has_one :cliente, through: :advance
  validates :empresa_id, presence: true
  validates :advance_id, presence: true
  validates :parcela, presence: true
  validates :data_vencimento, presence: true
  validates :valor, presence: true
  validates :atraso, presence: true
  validates :status, presence: true	
  validates :uuid, presence: true, uniqueness: {scope: :empresa_id}
  

  def diferenca
    self.valor * self.atraso
  end
end

app/controllers/api/item_advances_controller.rb
class Api::ItemAdvancesController < ApiController
  def index
	@item_advances = ItemAdvance.all
	render json: @item_advances.to_json
  end

  def show
  	@cliente = Cliente.first
  	@item_advance = ItemAdvance.find params[:id]
    render json: @item_advance.to_json
    #respond_to do |format|
    #  format.json { render json: @item_advance }
    #end
  end

  def create
    begin
      @item_advance = ItemAdvance.new(params[:item_advance])
      empresa_id = params[:item_advance][:empresa_id]
      advance_id = params[:item_advance][:advance_id]
      advance = Advance.find_by_empresa_id_and_uuid(params[:item_advance][:empresa_id],params[:item_advance][:advance_id])
      @item_advance.advance_id = advance.id
      @item_advance.status = 'A'

      if @item_advance.save
        render notice: 'ItemAdvance was successfully created.'
      else
        @errors = { :errors => @item_advance.errors.each {|m| m.to_s} }
        render json: @errors.to_json, :status => 200
      end
    rescue Exception => e
      @errors = { :errors => "create, record empresa: #{ empresa_id } and advance: #{advance_id} not found" }
      render json: @errors.to_json, :status => 200
    end
  end  

  def update
    begin
    @item_advance = ItemAdvance.find_by_empresa_id_and_uuid(params[:item_advance][:empresa_id],params[:item_advance][:uuid])
    if @item_advance.update_attributes(params[:item_advance])
      render(notice: 'item_advance was successfully updated.');
    else
      @errors = { :errors => @item_advance.errors.each {|m| m.to_s} }
      render json: @errors.to_json, status: 200
    end
    rescue Exception => e
      @errors = { :errors => 'update, record not found' }
      render json: @errors.to_json, :status => 200
    end

  end  

  def item_advances_today_and_city
    #@item_advances = ItemAdvance.joins(:cliente).where(uuid: [params[:item_advance]])
    @item_advances = ItemAdvance.joins(:cliente).where("DATE(data_pagamento) = ? and clientes.cidade = ? and item_advances.empresa_id = ?", params[:data_pagamento], params[:cidade], params[:empresa])
    respond_to do |format|
      format.json { render json: @item_advances }
    end
  end

  def destroy
    begin
      @item_advance = ItemAdvanceifcon.find_by_empresa_id_and_uuid(params[:empresa_id],params[:id])
      @item_advance.destroy
      @notice = { notice: "item_advance was successfully deleted" }
      render json: @notice.to_json, status:200
    rescue Exception => e
      @errors = { :errors => "unable to delete the item_advance"}
      render json: @errors.to_json, status: 200
    end
  end

end

app/controllers/item_advances_controller.rb
class ItemAdvancesController < ApplicationController
  before_action :signed_in_user

  respond_to :html

  def index
	  #@clientes = current_user.empresa_id.nil? ? Cliente.where(empresa_id: -1) : Cliente.where('empresa_id = ? and cidade = ?', current_user.empresa_id, current_user.cidade.nome)
    @item_advances = ItemAdvance.includes(:cliente).where("item_advances.empresa_id = ? and DATE(item_advances.data_vencimento) = ? and clientes.cidade = ?", current_user.empresa_id, Date.today.to_s, current_user.cidade.nome).order(order_by(current_user.empresa_id))    
  end

  def select_city
    @cidades = Cliente.cidades(current_user.empresa_id)
  end

  def summary_city
    @item_advances = ItemAdvance.joins(:cliente).select("clientes.cidade as cidade, sum(item_advances.valor) as valor, sum(item_advances.valor_pago) as valor_pago").where("DATE(data_vencimento) = ? and advances.empresa_id = ?", Date.today.to_s, current_user.empresa_id).group("clientes.cidade").order('clientes.cidade')
  end
 
  def select_client
    @clientes = current_user.empresa_id.nil? ? Cliente.where(empresa_id: -1) : Cliente.where('empresa_id = ? and cidade = ?', current_user.empresa_id, current_user.cidade.nome).order(:nome)
  end

  def item_advance_by_cliente
    @cliente = Cliente.find(params[:id])
  	@item_advance = ItemAdvance.joins(:cliente).where("DATE(data_vencimento) = ? and clientes.id = ?", Date.today.to_s, params[:id])
    respond_with(@item_advance) do |format|
      format.html { render :layout => !request.xhr? }
    end
  end

  def item_advance_by_city
    #@item_advances = ItemAdvance.includes(:advance, :cliente).where("item_advances.empresa_id = ? and DATE(item_advances.data_vencimento) = ? and clientes.cidade = ?", current_user.empresa_id, Date.today.to_s, params[:id]).order('advances.data, advances.uuid')
    @item_advances = ItemAdvance.includes(:advance, :cliente).where("item_advances.empresa_id = ? and DATE(item_advances.data_vencimento) = ? and clientes.cidade = ?", current_user.empresa_id, Date.today.to_s, params[:id]).order(order_by(current_user.empresa_id))
    respond_with(@item_advances) do |format|
      format.html { render :layout => !request.xhr? }
    end
  end

  def cobranca_diaria_by_city
    item_advance_by_city
  end

  def edit
    @item_advance = ItemAdvance.find(params[:id])
  end

  def update
    if params[:valor_pago].blank?
      redirect_to select_client_path, :flash => { :danger => "Informe o valor da parcela" } 
      return
    end 
    @item_advance = ItemAdvance.find(params[:parcela_id])
    respond_to do |format|
      if @item_advance.update_attributes(data_pagamento: Date.today.to_s, valor_pago: params[:valor_pago])
        flash[:success] = "Parcela foi atualizada com sucesso."
        #format.html { redirect_to item_advances_path, success: 'ItemAdvance was successfully updated.' }
        format.html { redirect_to select_client_path }
      else
        format.html { render action: 'edit' }
      end
    end
  end  

end

app/helpers/item_advances_helper.rb
module ItemAdvancesHelper
end

app/views/item_advances/cobranca_diaria_by_city.html.erb
<h3>Cobranca Diaria <%= Time.now.to_date.to_s %></h3>
<h4>Total Pago: <%= @item_advances.sum('valor_pago').to_f %></h4>

<table class="table">
	<thead>
		<th>Dt. Emp</th>
		<th>Cliente</th>
		<th>Parcela</th>
		<th>Vr.Parcela</th>
		<th>Vr.Pago</th>
		<th>Dev</th>
		<th>Atraso</th>
		<th>Dif</th>
	</thead>
	
	<tbody>
		<% @item_advances.each do |item| %>
		<tr>
			<td><%= link_to item.advance.data.to_s, advance_path(item.advance.id) %></td>
			<%#= link_to advance.id, advance_path(advance.id) %>
			<td><%= link_to item.cliente.nome, advance_path(item.advance.id) %></td>
			<td><%= item.parcela %></td>
			<td><%= item.valor.to_f %></td>
			<td><%= item.valor_pago.to_f %></td>
			<td><%= item.advance.saldo %></td>
			<td><%= item.atraso %></td>
			<td><%= item.diferenca %></td>
		</tr>
		<% end %>
	</tbody>

</table>

app/views/item_advances/edit.html.erb
<%= form_for(@item_advance) do |f| %>
  <%= hidden_field_tag 'parcela_id', "#{@item_advance.id}" %>
    <strong>Cliente: </strong> <%= @item_advance.cliente.nome %> <br />
    <strong>Dt Empres: </strong> <%= @item_advance.advance.data.to_s %> <br />
    <strong>Parcela: </strong> <%= @item_advance.parcela %> <br />
    <strong>Vencimento: </strong> <%= @item_advance.data_vencimento.to_s %> <br />
    <strong>Valor:</strong> <%= @item_advance.valor.to_f %> <br />
    <strong>Devedor:</strong> <%= @item_advance.advance.saldo.to_f %> <br />
    <strong>Atraso:</strong> <%= @item_advance.atraso.to_f %> <br />
    <strong>Diferença:</strong> <%= @item_advance.diferenca.to_f %> <br />

    <div>
      <strong>Valor Pago:</strong>
      <%= number_field_tag :valor_pago, nil, class: "form-control" %>
    </div>

    <div>
      <%= f.submit "Baixar", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/item_advances/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Total Cobranca</h3>
  </div>
  <div class="panel-body">
    Total Diária: <%= @item_advances.sum('valor')%> <br />
    Total Cobrado: <%= @item_advances.sum('valor_pago')%> <br />
  </div>
 
</div>

<% @item_advances.each do |item| %> 
   <% if item.data_pagamento.nil? %>
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= link_to item.cliente.nome, edit_item_advance_path(item) %></h3>
        </div>
          <div class="panel-body">
            Venc: <%= item.data_vencimento.to_s %> | Valor: <%= item.valor.to_f %> <br />
            Dt. Pgto: <%= item.data_pagamento.to_s %> | Valor Pago: <%= item.valor_pago.to_f %>
          </div>
      </div>
      <% else %>
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><%= item.cliente.nome %></h3>
        </div>
        <div class="panel-body">
            Venc: <%= item.data_vencimento.to_s %> | Valor: <%= item.valor.to_f %> <br />
            Dt. Pgto: <%= item.data_pagamento.to_s %> | Valor Pago: <%= item.valor_pago.to_f %>          
        </div>
       
     </div>
   <% end %>
<% end %>

app/views/item_advances/item_advance_by_city.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Total Cobrança</h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
      <dt>Diária:</dt>
      <dd><%= @item_advances.sum('valor').to_f %></dd>

      <dt>Cobrado:</dt>
      <dd><%= @item_advances.sum('valor_pago').to_f %></dd>
    </dl>
  </div>
</div>

<% @item_advances.each do |item| %> 
   <% if item.data_pagamento.nil? %>
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= item.cliente.nome %></h3>
        </div>
          <div class="panel-body">
            Venc: <%= item.data_vencimento.to_s %> | Valor: <%= item.valor.to_f %> <br />
            Dt. Pgto: <%= item.data_pagamento.to_s %> | Valor Pago: <%= item.valor_pago.to_f %>
            </div>
      </div>
      <% else %>
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><%= item.cliente.nome %></h3>
        </div>
        <div class="panel-body">
            Venc: <%= item.data_vencimento.to_s %> | Valor: <%= item.valor.to_f %> <br />
            Dt. Pgto: <%= item.data_pagamento.to_s %> | Valor Pago: <%= item.valor_pago.to_f %>          
        </div>
       
     </div>
   <% end %>
<% end %>

app/views/item_advances/item_advance_by_cliente.html.erb
<div>
<h3>Dados da Baixa</h3>

  <%= form_tag url_for(:controller => 'item_advances', :action => 'update', html: {class:"form-signin", role: "form"}), :method => 'put' do %>
    
    <% if @item_advance.size > 0 %>
        <%= hidden_field_tag 'parcela_id', "#{@item_advance[0].id}" %>
		<strong>Cliente: </strong> <%= @item_advance[0].cliente.nome %> <br />
		<strong>Dt Empres: </strong> <%= @item_advance[0].advance.data.to_s %> <br />
		<strong>Parcela: </strong> <%= @item_advance[0].parcela %> <br />
		<strong>Vencimento: </strong> <%= @item_advance[0].data_vencimento.to_s %> <br />
		<strong>Valor:</strong> <%= @item_advance[0].valor.to_f %> <br />
		<strong>Devedor:</strong> <%= @item_advance[0].advance.saldo.to_f %> <br />
		<strong>Atraso:</strong> <%= @item_advance[0].atraso.to_f %> <br />
		<strong>Diferença:</strong> <%= @item_advance[0].diferenca.to_f %> <br />

		<div>
		  <strong>Valor Pago:</strong>
		  <%= number_field_tag :valor_pago, nil, class: "form-control" %>
		</div>

		<div>
		 <%= submit_tag "Baixar", class: "btn btn-primary" %>
		</div>
	<% else %>
	   <div>
	    <p>
	      Não existe parcela para o cliente <br />
	      <strong><%= @cliente.nome%></strong> 
	      na data <%= Date.today.to_s %>
	    </p>
	   </div>
	<% end %>
  <% end %>

</div>

app/views/item_advances/overview_city.html.erb
<h3>Resumo por Cidade</h3>
<% @item_advances.each do |item| %> 
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= item.cidade %></h3>
    </div>
    <div class="panel-body">
      Total Diária:  <%= item.valor %> <br />
      Total Cobrado: <%= item.valor_pago %> <br />
    </div>
  </div>
<% end %>

app/views/item_advances/select_city.html.erb
<h4>Cobrança Diária</h4>

<div id='select_city'>
  <%= collection_select(nil, :cidade_id, @cidades, :id, :cidade, {:prompt => 'Selecione a cidade'}, class: "form-control") %>
</div>
<br />
<div id='cobranca_diaria'>
  
</div>

<script type="text/javascript">

jQuery(function($) {
  // when the #country field changes
  $("#_cidade_id").change(function() {
    // make a POST call and replace the content
    var conta = $('select#_cidade_id :selected').val();
    if(conta == "") conta="0";
  //  jQuery.get('/item_advance_by_city/' + conta, function(data){
  //      $("#cobranca_diaria").html(data);
  //  })
    jQuery.get('/cobranca_diaria_by_city/' + conta, function(data){
        $("#cobranca_diaria").html(data);
    })

    return false;
  });

})


</script>

app/views/item_advances/select_client.html.erb
<hr>

<div id='select_client'>
  <strong>Informe um cliente</strong> <br />
  <%= collection_select(nil, :cliente_id, @clientes, :id, :nome, {:prompt => 'Selecione o Cliente'}, class: "form-control") %>
</div>

<div id='baixa_item_advance'>
  
</div>


<script type="text/javascript">

jQuery(function($) {
  // when the #country field changes
  $("#_cliente_id").change(function() {
    // make a POST call and replace the content
    var conta = $('select#_cliente_id :selected').val();
    if(conta == "") conta="0";
    jQuery.get('/item_advance_by_cliente/' + conta, function(data){
        $("#baixa_item_advance").html(data);
    })
    return false;
  });

})


</script>

app/views/item_advances/summary_city.html.erb
<h3>Resumo por Cidade</h3>
<% @item_advances.each do |item| %> 
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= item.cidade %></h3>
    </div>
    <div class="panel-body">
      Total Diária:  <%= item.valor %> <br />
      Total Cobrado: <%= item.valor_pago %> <br />
    </div>
  </div>
<% end %>