config/routes.rb
Emprestimo::Application.routes.draw do
  resources :sessions
  resources :item_advances#, only: [:index, :edit, :update]
  resources :advances
  resources :caixas
  
  match '/item_advance_by_cliente/:id', :controller=>'item_advances', :action => 'item_advance_by_cliente', via: [:get]
  match '/item_advance_by_city/:id', :controller=>'item_advances', :action => 'item_advance_by_city', via: [:get]
  match '/cobranca_diaria_by_city/:id', :controller=>'item_advances', :action => 'cobranca_diaria_by_city', via: [:get]
  
  match '/advance_by_city/:id', :controller=>'advances', :action => 'advance_by_city', via: [:get]
  match '/select_client/', :controller=>'item_advances', :action => 'select_client', via: [:get]
  match '/summary_city/', :controller=>'item_advances', :action => 'summary_city', via: [:get]
  match '/select_city/', :controller=>'item_advances', :action => 'select_city', via: [:get]
  namespace "api" do
    resources :cidades
    resources :clientes
    resources :advances, except: [:destroy]
    resources :item_advances
    resources :empresas do
      resources :advances, only: [:destroy]
      resources :item_advances, only: [:destroy]
    end
    resources :caixas
    resources :lancamento_caixas
    post "cidades_uuid" => "cidades#cidades_uuid", :as => "cidades_uuid",  via: [:post]
    post "clientes_uuid" => "clientes#clientes_uuid", :as => "clientes_uuid",  via: [:post]
    #post "item_advances_today_and_city" => "item_advances#item_advances_today_and_city", :as => "item_advances_today_and_city",  via: [:post]
    post "item_advances_today_and_city" => "item_advances#item_advances_today_and_city",  via: [:post]
    get "is_active" => "servers#is_active", :as => "is_active", via: [:get]
  end
  #root to: 'item_advances#index'
  root to: 'sessions#new'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'  

end
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav role="navigation" class="navbar navbar-default">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand"><%= full_title(yield(:title)) %></a>
      </div>
      <!-- Collection of nav links and other content for toggling -->
      <% if signed_in? %>
        <div id="navbarCollapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if current_user.nivel == User::Nivel::SUPERVISOR %>
              <li><%= link_to "Caixa Diário", caixas_path %></li>
              <li><%= link_to "Acompanhamento", advances_path %></li>
              <li><%= link_to "Cobrança Diária", select_city_path %></li>
              <li><%= link_to "Resumo por Cidade", summary_city_path %></li>
            <% else %>
              <li><%= link_to "Cobrança Diária", item_advances_path %></li>
              <li><%= link_to "Baixar Parcela", select_client_path %></li>
            <% end %>
            <li><%= link_to "Sair", signout_path, method: "delete" %> </li>
          </ul>
          <!--             
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Login</a></li>
          </ul>
          -->        
        </div>
      <% end %>
    </nav>
  </div>

  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%#= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>


</body>
</html>